version: '3.7'
services:
  mysql_db_container:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./config/mysql.env
    ports:
      - 3308:3308
    volumes:
      - mysql_db_data_container:/var/lib/mysql

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
      ADMINER_DESIGN: galkaev
    ports:
      - 8083:8083


volumes:
  mysql_db_data_container: